# index 页面配置
index:
  # 顶部大图
  banner_img: /img/shumatsu.jpg
  slogan:
    enable: true
    text: Hello!

post:
  math:
    enable: true
    specific: true
    engine: mathjax

web_analytics:  # 网页访问统计
  enable: true
  baidu: 25bbd832c304327384cf5e1fbcaf70a1

navbar:
  blog_title: Song's bolg

about:
  name: "Song"
  intro: "希望你快乐"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/heyitsmine', tip: 'GitHub' }
    - { class: 'iconfont icon-twitter-fill', link: 'https://twitter.com/HuashuoZs', tip: 'Twitter' }